/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiuye_jni_NewString */

#ifndef _Included_com_xiuye_jni_NewString
#define _Included_com_xiuye_jni_NewString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiuye_jni_NewString
 * Method:    newString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiuye_jni_NewString_newString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
